// @ts-check
import antfu from '@antfu/eslint-config'

export default antfu(
  {
    type: 'app',
    typescript: true,
    react: true,
    // Only src/ is the real, live project (see CLAUDE.md) — src.prestige/ is
    // unmaintained third-party reference material and NetscriptDefinitions.d.ts
    // is regenerated by Viteburner, so neither should ever be linted/fixed.
    ignores: ['src.prestige/**', 'NetscriptDefinitions.d.ts', 'dist/**'],
  },
  {
    // Bitburner's NS API is reached via the game's own globals
    // (`eval("window")`/`eval("document")`, see CLAUDE.md), and every
    // top-level script needs a `main` export the game calls directly.
    rules: {
      'no-eval': 'off',
      'no-console': 'off',
      // This project never runs through Vite's dev server / Fast Refresh —
      // ui.app.ts mounts React once into the live game window and exits
      // (see CLAUDE.md's "ui.app.ts" section), and *.app.tsx files routinely
      // export a script's `main` entrypoint alongside internal, unexported
      // render components. There's no HMR boundary here for this rule to
      // protect.
      'react-refresh/only-export-components': 'off',
    },
  },
)
