import type { Plugin } from 'vite'
import { readdirSync, readFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'

/**
 * Recursively lists absolute paths of files under `dir` whose path relative
 * to `base` (forward-slash-joined, so it matches in-game path conventions)
 * satisfies `filter`.
 */
export function walk(dir: string, filter: (relPath: string) => boolean, base: string = dir): string[] {
  const out: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      out.push(...walk(full, filter, base))
    }
    else if (filter(relative(base, full).split(sep).join('/'))) {
      out.push(full)
    }
  }
  return out
}

function buildSetupScript(files: Record<string, string>): string {
  const entries = Object.keys(files)
    .sort()
    .map(name => `    ${JSON.stringify(name)}: ${JSON.stringify(files[name])},`)
    .join('\n')
  return `// AUTO-GENERATED by \`vite build\` — do not edit by hand.
// Deploys this project's entire game filesystem in one shot: run it once
// (e.g. \`run setup.js\`) on "home" to write every file below to disk,
// overwriting any file already there. Deletes itself once done.
/** @param {NS} ns */
export async function main(ns) {
    const files = {
${entries}
    };
    for (const [filename, content] of Object.entries(files)) {
        ns.write(filename, content, "w");
    }
    ns.tprint(\`setup.js: wrote \${Object.keys(files).length} file(s).\`);
    ns.rm(ns.getScriptName());
}
`
}

/**
 * Only active for `vite build`. Rolls the whole project into one Bitburner
 * script: Rollup's `preserveModules` (set in vite.config.ts) keeps every
 * source file as its own output chunk instead of bundling them together —
 * each deployed script must stay standalone and importable by its sibling
 * files at runtime, exactly like viteburner's live push already treats
 * them — so this hook just reads those already-correct per-file chunks back
 * out of the bundle, folds them (plus the untransformed `.script`/`.txt`
 * files) into one `files` map, and replaces the whole multi-file bundle with
 * a single `setup.js` asset built from it.
 */
export function setupBundlePlugin(srcDir: string): Plugin {
  return {
    name: 'bundle-into-setup-script',
    generateBundle(_options, bundle) {
      const files: Record<string, string> = {}
      for (const [fileName, output] of Object.entries(bundle)) {
        if (output.type === 'chunk') {
          files[fileName] = output.code
        }
        delete bundle[fileName]
      }
      for (const full of walk(srcDir, rel => /\.(?:script|txt)$/.test(rel))) {
        files[relative(srcDir, full).split(sep).join('/')] = readFileSync(full, 'utf8')
      }
      this.emitFile({ type: 'asset', fileName: 'setup.js', source: buildSetupScript(files) })
    },
  }
}
